apiVersion: v1
kind: Service
metadata:
  name: medassist
  labels:
    app: medassist
spec:
  type: LoadBalancer
  selector:
    app: medassist
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
